name: 'NoteHub actions'
description: 'Generate new journal file'
author: 'Sound1ab'
inputs:
  COMMAND:
    required: true
    description: 'Command to execute'
  GH_TOKEN:
    required: false
    description: 'GitHub access token'
  REPO:
    required: false
    description: 'Repo to generate journal file in'
    default: 'NoteHub.Notebook'
  ROOT_DIR:
    required: false
    description: 'Directory containing journal template'
    default: 'Journal'

runs:
  using: 'node12'
  main: './dist/index.js'
