name: 'NoteHub actions'
description: 'Generate new journal file'
author: 'Sound1ab'
inputs:
  GH_TOKEN:
    required: false
    description: 'GitHub access token'
  REPO:
    required: false
    description: 'Repo to generate journal file in'
    default: 'NoteHub.Notebook'
  COMMAND:
    required: false
    description: 'Command to execute'
    default: 'Journal'
runs:
  using: 'node12'
  main: '../../../dist/index.js'
