name: 'Generate journal entry'
description: 'Generate new journal file'
author: 'Sound1ab'
inputs:
  GH_TOKEN:
    required: true
    description: 'GitHub access token'
  repo:
    required: true
    description: 'GitHub access token'
    default: ${{ secrets.REPO }}
runs:
  using: 'node12'
  main: '../../../dist-createJournalEntry/index.js'
