name: 'build'
on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: ./.github/actions/install-dependencies
        if: steps.cache.outputs.cache-hit != 'true'
  eslint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: ./.github/actions/run-linter-check
  typescript:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: ./.github/actions/run-typescript-check
  build:
    needs: [eslint, typescript]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: ./.github/actions/build
      - uses: actions/upload-artifact@v2
        with:
          name: lib
          path: ./lib
  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: lib
          path: ./lib
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: ./.github/actions/package
      - uses: actions/cache@v2
        id: cache
        with:
          path: './dist'
          key: ${{ runner.os }}-modules-${{ hashFiles('./dist') }}
#  generate-journal-entry:
#    needs: package
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/download-artifact@v2
#        with:
#          name: dist
#      - uses: ./.github/actions/install-dependencies.yml
#      - uses: ./.github/actions/generate-journal-entry.yml
#      with:
#        GH_TOKEN: ${{ secrets.GH_TOKEN }}
