name: 'create-journal-entry'
on:
  schedule:
    - cron: '1 */24 * * *'
  workflow_dispatch:

jobs:
  create-journal-entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ secrets.REPO }}
          COMMAND: 'create-journal-entry'
