name: 'create-journal-entry'
on:
  schedule:
    - cron: '1 */24 * * *'

jobs:
  create-journal-entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: './dist'
          key: ${{ runner.os }}-modules-${{ hashFiles('./dist') }}
      - uses: ./.github/actions/create-journal-entry
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ secrets.REPO }}
          COMMAND: 'create-journal-entry'
