name: 'generate-journal-entry'
on:
  push:
    branches:
      - main

jobs:
  generate-journal-entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: './dist'
          key: ${{ runner.os }}-modules-${{ hashFiles('./dist') }}
      - uses: ./.github/actions/generate-journal-entry
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
